### ISSUE TITLE
Correct needed ansible version

### ISSUE THREAD

**Issue by Sheogorath-SI** [infOpen/ansible-role-fail2ban#2]
{{ role_path }} needs Ansible 1.8 or higher

https://docs.ansible.com/ansible/playbooks_variables.html

**Comment by achaussier** [comment]
Hello,

Thanks, I fix this point now

**Comment by achaussier** [comment]
Fix included in https://github.com/infOpen/ansible-role-fail2ban/releases/tag/0.1.2

Thanks
